### ISSUE TITLE
Link the repo to pub dev

### ISSUE THREAD

**Issue by Kiruel** [Scandit/scandit-flutter-datacapture-barcode#2]
Hi !
Can be nice if you link this repo to pub.dev => https://pub.dev/packages/scandit_flutter_datacapture_barcode

Thanks !

**Comment by ScanditSupport** [comment]
Hi @Kiruel,

We have added it as a feature request. 

In case you encounter any troubles, please reach out directly to us
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
